### ISSUE TITLE
Creating routine without selecting variables or observables creates an opaque exception

### ISSUE THREAD

**Issue by finnoshea** [xopt-org/Badger#41]
To reproduce this bug:
1) click the + next to the Search bar
2) select an algorithm (I choose UCB)
3) select a environment
4) click the save button

The exception:
```
Traceback (most recent call last):
  File "/Users/foshea/Documents/Projects/badger/badger_repo/src/badger/gui/default/components/routine_page.py", line 716, in save
    routine = self._compose_routine()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/foshea/Documents/Projects/badger/badger_repo/src/badger/gui/default/components/routine_page.py", line 659, in _compose_routine
    routine = Routine(
              ^^^^^^^^
  File "/Users/foshea/anaconda3/envs/badger/lib/python3.11/site-packages/xopt/base.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/Users/foshea/anaconda3/envs/badger/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Routine
vocs
  Value error, this generator only supports single objective [type=value_error, input_value=VOCS(variables={}, constr...ants={}, observables=[]), input_type=VOCS]
    For further information visit https://errors.pydantic.dev/2.6/v/value_error
```

**Comment by roussel-ryan** [comment]
Error improvements in recent PRs handle this
